name: E2E Testing

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: none

jobs:
  e2e:
    name: "Run E2E tests (use wordpress:${{ matrix.wordpress }} image)"
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wordpress:
          - php8.1
          - php8.2
          - php8.3
          - php8.4
          - php8.5
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js environment
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Set up PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Run Playwright E2E tests
        run: npm run test:e2e
        env:
          WP_VERSION: ${{ matrix.wordpress }}

      - name: Upload test results
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: failure()
        with:
          name: playwright-test-results-${{ matrix.wordpress }}
          path: test-results/
          retention-days: 3

  e2e-bundle:
    name: Run E2E tests on the generated plugin
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Generate self-contained package
        run: |
          git archive --format=tar --prefix=two-factor-provider-webauthn/ HEAD | (cd /var/tmp/ && tar xf -)
          (cd /var/tmp/two-factor-provider-webauthn && composer install --no-dev --no-interaction && composer remove --update-no-dev --no-interaction composer/installers cweagans/composer-patches && rm -rf composer.lock composer.json patches vendor/madwizard/webauthn/.github vendor/madwizard/webauthn/conformance vendor/madwizard/webauthn/tests vendor/psr/log/Psr/Log/Test vendor/psr/http-message/docs vendor/typisttech)

      - name: Patch docker-compose.yml
        run: |
          sed -i 's!- .:!- /var/tmp/two-factor-provider-webauthn:!' docker-compose.yml

      - name: Set up Node.js environment
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Run Playwright E2E tests
        run: npm run test:e2e
        env:
          WP_VERSION: php8.3

      - name: Upload test results
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: failure()
        with:
          name: playwright-test-results-bundle
          path: test-results/
          retention-days: 3

  e2e-vip:
    name: Run E2E tests on VIP Dev Environment
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js environment
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Set up PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Install VIP CLI
        run: npm i -g @automattic/vip

      - name: Run Playwright E2E tests
        run: npm run test:e2e:vip

      - name: Upload test results
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: failure()
        with:
          name: playwright-test-results-vip
          path: test-results/
          retention-days: 3
