name: Static Code Analysis

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: none

jobs:
  psalm:
    name: Analyze the code with Psalm
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          disable-file-monitoring: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            azure.archive.ubuntu.com:80
            cdn.fwupd.org:443
            cdn.jsdelivr.net:443
            dl.cloudsmith.io:443
            downloads.wordpress.org:443
            getcomposer.org:443
            github.com:443
            objects.githubusercontent.com:443
            packagist.org:443
            release-assets.githubusercontent.com:443
            repo.packagist.org:443
            setup-php.com:443

      - name: Check out source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          coverage: none
          php-version: '8.3'

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Install Psalm
        run: npm run psalm:install

      - name: Run psalm
        run: composer psalm -- --output-format=github
